import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/global/Navbar'
import { NavbarHight } from '@/constant/constants'
import { Toaster } from '@/components/ui/toaster'
import QueryProvider from '@/components/providers/QueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <QueryProvider>
            <Toaster />
            <div className='text-gray-700 bg-gray-50'>
            <Navbar/>
            <div className='' style={{marginTop:NavbarHight}}>
                {children}
            </div>
            </div>
        </QueryProvider>
      </body>
    </html>
  )
}
